src/controllers/AssistantController.py
from dotenv import get_key
from flask import Blueprint, flash, jsonify, render_template, redirect, request, url_for
import requests

assistant_bp = Blueprint('assistant', __name__)

# 🔑 Clave de Gemini
api_key = get_key(".env", "API_KEY")
API_URL = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={api_key}"

# 📌 Ruta para mostrar el chatbox
@assistant_bp.route('/chatbox')
def chatbox():
    return render_template('screens/Chatbox/chatbox.html')

# 📌 Ruta para enviar mensajes a Gemini (proxy seguro)
@assistant_bp.route('/ask_gemini', methods=['POST'])
def ask_gemini():
    user_text = request.json.get("text", "")  # ✅ request está ahora importado
    if not user_text:
        return jsonify({"error": "Texto vacío"}), 400

    payload = {
        "contents": [
            {
                "parts": [
                    {"text": user_text}
                ]
            }
        ]
    }

    try:
        # ✅ requests está ahora importado
        response = requests.post(API_URL, json=payload)
        
        # Verificar si la respuesta fue exitosa
        if response.status_code == 200:
            return jsonify(response.json())
        else:
            return jsonify({"error": f"Error de API: {response.status_code}"}), 500
            
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@assistant_bp.route('/rci')
def rci():
    return render_template('screens/RCI/rci.html')

src/controllers/ChatController.py
import datetime
from flask import Blueprint, flash, render_template, redirect, url_for, request, session
from ..services.ChatRepositotyImpl import ChatRepositoryImpl

repository = ChatRepositoryImpl()

def formatear_fecha(timestamp):
    """
    Formatea la fecha para mostrarla en el chat
    """
    if not timestamp:
        return ''
    
    ahora = datetime.datetime.now()
    
    # Convertir a datetime si es string
    if isinstance(timestamp, str):
        try:
            # Manejar diferentes formatos de fecha
            if 'T' in timestamp:
                timestamp = datetime.datetime.fromisoformat(timestamp.replace('Z', '+00:00'))
            else:
                timestamp = datetime.datetime.strptime(timestamp, '%Y-%m-%d %H:%M:%S')
        except:
            return ''
    
    if timestamp.date() == ahora.date():
        return timestamp.strftime('%H:%M')
    elif timestamp.year == ahora.year:
        return timestamp.strftime('%d/%m')
    else:
        return timestamp.strftime('%d/%m/%Y')

chat_bp = Blueprint('chat', __name__)

@chat_bp.route('/crearChat', methods=['POST'])
def crear_chat():
    id_emisor = session.get('user_uid')
    id_receptor = request.form.get('id_receptor')

    if not id_emisor or not id_receptor:
        flash('no puedes crear un chat sin dos ids', 'error')
        return redirect(url_for('ofertas.listar_ofertas'))

    id_chat = repository.crear_chat(id_emisor, id_receptor)
    return redirect(url_for('ofertas.listar_ofertas'))

@chat_bp.route('/obtenerChats')
def obtener_chats():
    id_usuario = session.get('user_uid')
    
    if not id_usuario:
        flash('Debes iniciar sesión para ver tus chats', 'error')
        return redirect(url_for('auth.login'))

    chats = []
    try:
        # El repositorio ya nos da los chats procesados, con la información del otro usuario y el último mensaje.
        chats = repository.obtener_chats_usuario(id_usuario)
    
    except Exception as e:
        print(f"Error al obtener y procesar los chats: {e}")
        flash('Error al cargar los chats', 'error')

    return render_template('screens/Bandeja_entrada/Bandeja_entrada.html', chats=chats)

src/controllers/HomeController.py
import json
from dotenv import get_key
from flask import Blueprint, render_template, request
from ..services.MapRepositoryImpl import MapRepositoryImpl

mapRepository = MapRepositoryImpl()

home_bp = Blueprint('home', __name__)


@home_bp.route('/mapa')
def mapa():
    api_key = get_key(".env","MAPS_API_KEY")
    data = mapRepository.getLocations()

    location_dict = [map.to_dict() for map in data]
    data_json = json.dumps(location_dict)
    return render_template('screens/Mapa/mapa.html', locations=data_json, google_maps_api_key=api_key)

# ---------------- Mapa ----------------
@home_bp.route('/bandeja_entrada')
def bandeja_entrada():
    return render_template('screens/Bandeja_entrada/Bandeja_entrada.html')

    

src/controllers/LoginController.py
from flask import Blueprint, flash, render_template, redirect, request, url_for, session
from dotenv import get_key
import requests
from ..services.AuthRepositoryImpl import AuthRepositoryImpl
from ..services.UserRepository import UserRepositoryImpl

repository = AuthRepositoryImpl()
userRepository = UserRepositoryImpl()

login_bp = Blueprint("login", __name__)

baseDir = 'screens/login/'

@login_bp.before_request
def load_user():
    if 'user_uid' in session:
        user_info = repository.get_user(session['user_uid'])
        if user_info:
            session['user'] = user_info


FIREBASE_API_KEY = get_key('.env', 'FIREBASE_API_KEY')

@login_bp.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        # Aquí iría la lógica de autenticación

        if not email or not password:
            flash(f'Error en el inicio de sesión: Rellene el formulario de login', 'error')
            return redirect(url_for('login.login'))

        try:
            response = requests.post(
                f'https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key={FIREBASE_API_KEY}',
                json={
                    'email': email,
                    'password': password,
                    'returnSecureToken': True
                    }
                )

            data = response.json()
            if 'idToken' in data:
                decoded_token = repository.authenticate_user(data['idToken'])

                if decoded_token:
                    session['user_uid'] = decoded_token['uid']
                    session['email'] = decoded_token['email']
                    session['user_token'] = data['idToken']
                    
                        
                    flash('¡Inicio de sesión exitoso!', 'success')
                    return redirect(url_for('ofertas.listar_ofertas'))
            
            flash('Credenciales inválidas. Por favor intenta nuevamente o registrate.', 'error')
            return redirect(url_for('login.login'))
        except Exception as e:
            flash(f'Error en el inicio de sesión: {str(e)}', 'error')
            return redirect(url_for('login.login'))
    return render_template(baseDir + 'login.html', full_screen=True)
    
@login_bp.route('/registro', methods=['GET','POST'])
def registro():
    if request.method == 'GET':
        return render_template(baseDir + 'registro.html', full_screen=True)
    else:
        email = request.form.get('email')
        password = request.form.get('password')
        confirmar = request.form.get('confirmar')

        rol = request.form.get('rol')
        name = request.form.get('name')

        if password != confirmar:
            return "Las contraseñas no coinciden", 400

        try:
            result = repository.create_user(email, password)

            if result['success']:
                userRepository.create_user(
                    uid=result['user']['uid'],
                    name=name,
                    email=email,
                    location='Managua, nicaragua',
                    rol=rol
                )
            
                flash('¡Registro exitoso! Ahora puedes iniciar sesión.', 'success')
                return redirect(url_for('login.login'))
            else:
                flash(f"Error en el registro: {result.get('error', 'Error desconocido')}", 'error')
                return redirect(url_for('login.registro'))
        except Exception as e:
            flash(f"Error al registrar usuario: {str(e)}", 'error')
            return str(e), 400

@login_bp.route('/logout')
def logout():
    session.clear()
    flash('Has cerrado sesión exitosamente.', 'success')
    return redirect(url_for('login.login'))

templates/base/BaseAdmin.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
  <link href="{{ url_for('static', filename='css/central-coffe-theme.css')}}" rel="stylesheet" />
</head>

<body class="{% if full_screen %}full-screen{% endif %}">
  {% if not full_screen %}
  <!-- Navbar para móviles -->
  <nav class="navbar navbar-dark bg-dark d-lg-none align-items-center">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasSidebar"
        aria-controls="offcanvasSidebar">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="logo text-center text-white">CentralCoffee</div>
  </nav>

  <!-- Sidebar para móviles (Offcanvas) -->
  <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasSidebar" aria-labelledby="offcanvasSidebarLabel">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="offcanvasSidebarLabel">Menú</h5>
      <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body d-flex flex-column justify-content-between">
      <div>
        <div class="logo">
          <picture>
            <img src="{{url_for('static', filename='img/logo.png')}}" class="img-fluid w-75 align-content-center"
              alt="image desc" />
          </picture>
          CentralCoffee
        </div>
        <div class="menu">
          <a href="{{ url_for('ofertas.listar_ofertas') }}"><i class="bi bi-tag"></i>Oferta</a>
          <a href="{{ url_for('home.mapa') }}"><i class="bi bi-map"></i>Mapa</a>
          <a href="{{ url_for('chat.obtener_chats') }}"><i class="bi bi-inbox"></i>Bandeja de entrada</a>
          <a href="{{ url_for('assistant.chatbox') }}"><i class="bi bi-cpu"></i>Asistente IA</a>
          <a href="{{ url_for('assistant.rci') }}"><i class="bi bi-images"></i>Reconocimiento con imagen</a>
          <a href="{{ url_for('profile.profile') }}">
            <i class="bi bi-person"></i>Perfil</a>
        </div>
      </div>
      <div class="bottom">
        <div class="switch">
          <span>Light Mode</span>
          <input type="checkbox" class="theme-switch" />
        </div>
        <a href="{{ url_for('login.logout') }}" class="btn logout-button">Logout</a>
      </div>
    </div>
  </div>
  {% endif %}

  <div class="container-main">
    {% if not full_screen %}
    <!-- Sidebar para DESKTOP -->
    <div class="sidebar-desktop d-none d-lg-flex">
      <div>
        <div class="logo">
          <picture>
            <img src="{{url_for('static', filename='img/logo.png')}}" class="img-fluid w-50 align-content-center"
              alt="image desc" />
          </picture>
          CentralCoffee
        </div>

        <div class="menu">
          <a href="{{ url_for('ofertas.listar_ofertas') }}"><i class="bi bi-tag"></i>Oferta</a>
          <a href="{{ url_for('home.mapa') }}"><i class="bi bi-map"></i>Mapa</a>
          <a href="{{ url_for('chat.obtener_chats') }}"><i class="bi bi-inbox"></i>Bandeja de entrada</a>
          <a href="{{ url_for('assistant.chatbox') }}"><i class="bi bi-cpu"></i>Asistente IA</a>
          <a href="{{ url_for('assistant.rci') }}"><i class="bi bi-images"></i>Reconocimiento con imagen</a>
          <a href="{{ url_for('profile.profile') }}">
            <i class="bi bi-person"></i>Perfil</a>
        </div>
      </div>
      <div class="bottom">
        <div class="switch">
          <span>Light Mode</span>
          <input type="checkbox" class="theme-switch" />
        </div>
        <a href="{{ url_for('login.logout') }}" class="btn logout-button">Logout</a>
      </div>
    </div>
    {% endif %}

    <!-- Contenido principal -->
    <div class="main-content">
      {% block body %}
      <!-- Aquí se renderiza el contenido específico de cada página -->
      {% endblock %}
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
  <script src="{{ url_for('static', filename='js/theme-switcher.js') }}"></script>
</body>

</html>